name: 🤔 Volunteer
description: Some volunteer help
title: "[Volunteer] <title>"
labels: ["status: volunteer wanted"]
body:
- type: textarea
  attributes:
    label: Volunteer help
    placeholder: >
      your need volunteer help here;
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      Please read the [Contribution Guideline](https://shenyu.apache.org/community/contributor) before submitting the PR

